# Rebuilds data/dict.js for the Add Word feature.
#
# Sources:
#   1. jmdict-simplified "eng-common" JSON (all JMdict entries marked common) —
#      download the latest jmdict-eng-common-*.json.zip from
#      https://github.com/scriptin/jmdict-simplified/releases and unzip into tools/cache/
#   2. The existing data/dict.js, which supplies JLPT level tags and any
#      JLPT-list words (rare N1 vocab etc.) that JMdict doesn't mark common.
#
# Output rows: [expression, reading, meaning, jlptLevel]  (level 0 = common, not on a JLPT list)
# Entries with several common readings are emitted once per reading so
# typing any of them by ear finds the word.

param(
  [string]$JsonPath,
  [string]$OutPath = "$PSScriptRoot\..\data\dict.js"
)
$ErrorActionPreference = "Stop"

if (-not $JsonPath) {
  $JsonPath = Get-ChildItem "$PSScriptRoot\cache\jmdict-eng-common*.json" | Select-Object -First 1 -ExpandProperty FullName
}

Add-Type -AssemblyName System.Web.Extensions
$ser = New-Object System.Web.Script.Serialization.JavaScriptSerializer
$ser.MaxJsonLength = [int]::MaxValue
$ser.RecursionLimit = 1000

Write-Host "Parsing $JsonPath ..."
$doc = $ser.DeserializeObject([IO.File]::ReadAllText($JsonPath))

# --- JLPT levels + extra rows from the current dict.js ---
Write-Host "Reading JLPT tags from $OutPath ..."
$oldTxt = [IO.File]::ReadAllText($OutPath)
$body = [regex]::Match($oldTxt, '(?s)const DICT = \[(.*)\];').Groups[1].Value.Trim().TrimEnd(',')
$old = $ser.DeserializeObject("[$body]")
# level 0 rows are JMdict filler from a previous build, not JLPT data - skip them
# so the script can safely re-run on its own output
$jlpt = @{}
foreach ($row in $old) { if ([int]$row[3] -gt 0) { $jlpt["$($row[0])|$($row[1])"] = [int]$row[3] } }

# The original dict.js was built without the N4 word list, so layer the tags in
# from the source CSV: https://raw.githubusercontent.com/elzup/jlpt-word-list/master/src/n4.csv
$n4 = @()
$n4Path = "$PSScriptRoot\cache\n4.csv"
if (Test-Path $n4Path) {
  $n4 = Import-Csv $n4Path -Encoding UTF8
  foreach ($r in $n4) {
    $key = "$($r.expression)|$($r.reading)"
    if (-not $jlpt.ContainsKey($key)) { $jlpt[$key] = 4 }
  }
} else {
  Write-Warning "tools/cache/n4.csv not found - N4 level tags will be missing."
}

$list = New-Object System.Collections.Generic.List[object]
$seen = New-Object 'System.Collections.Generic.HashSet[string]'

foreach ($w in $doc["words"]) {
  $kanjis = @($w["kanji"]); $kanas = @($w["kana"])

  $expr = $null
  foreach ($kj in $kanjis) { if ($kj["common"]) { $expr = $kj["text"]; break } }
  if (-not $expr -and $kanjis.Count) { $expr = $kanjis[0]["text"] }

  # all common readings (skip search-only "sk" forms); fall back to the first reading
  $readings = New-Object System.Collections.Generic.List[string]
  foreach ($kn in $kanas) {
    if ($kn["tags"] -contains "sk") { continue }
    if ($kn["common"]) { $readings.Add($kn["text"]) }
  }
  if ($readings.Count -eq 0) {
    foreach ($kn in $kanas) { if ($kn["tags"] -notcontains "sk") { $readings.Add($kn["text"]); break } }
  }
  if ($readings.Count -eq 0) { continue }
  if ($readings.Count -gt 3) { $readings = $readings.GetRange(0, 3) }
  if (-not $expr) { $expr = $readings[0] }

  # first three distinct glosses across senses
  $gl = New-Object System.Collections.Generic.List[string]
  foreach ($s in @($w["sense"])) {
    foreach ($g in @($s["gloss"])) {
      $t = $g["text"]
      if ($t -and -not $gl.Contains($t)) { $gl.Add($t) }
      if ($gl.Count -ge 3) { break }
    }
    if ($gl.Count -ge 3) { break }
  }
  if ($gl.Count -eq 0) { continue }
  $m = $gl -join ", "

  foreach ($r in $readings) {
    if ($seen.Add("$expr|$r")) {
      $lvl = 0
      if ($jlpt.ContainsKey("$expr|$r")) { $lvl = $jlpt["$expr|$r"] }
      $list.Add([pscustomobject]@{ w = $expr; k = $r; m = $m; lvl = $lvl })
    }
  }
}

# keep JLPT-list words JMdict doesn't consider common (their gloss comes from the old file)
foreach ($row in $old) {
  if ($seen.Add("$($row[0])|$($row[1])")) {
    $list.Add([pscustomobject]@{ w = $row[0]; k = $row[1]; m = $row[2]; lvl = [int]$row[3] })
  }
}
foreach ($r in $n4) {
  if ($seen.Add("$($r.expression)|$($r.reading)")) {
    $list.Add([pscustomobject]@{ w = $r.expression; k = $r.reading; m = ($r.meaning -replace '; ', ', '); lvl = 4 })
  }
}

$list = $list | Sort-Object @{e = { $_.lvl }; Descending = $true }, @{e = { $_.k }}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("// Lookup dictionary for the Add Word feature. Generated by tools/build-dict.ps1 - do not edit by hand.")
[void]$sb.AppendLine("// Sources: JMdict via jmdict-simplified (EDRDG licence, CC BY-SA 4.0, https://www.edrdg.org/jmdict/j_jmdict.html)")
[void]$sb.AppendLine("//          + JLPT level tags from elzup/jlpt-word-list.")
[void]$sb.AppendLine("// Format: [expression, reading, meaning, jlptLevel]  (0 = common word, not on a JLPT list)")
[void]$sb.AppendLine("const DICT = [")
foreach ($e in $list) {
  $w = $e.w.Replace('\', '\\').Replace('"', '\"')
  $k = $e.k.Replace('\', '\\').Replace('"', '\"')
  $m = $e.m.Replace('\', '\\').Replace('"', '\"')
  [void]$sb.AppendLine("[`"$w`",`"$k`",`"$m`",$($e.lvl)],")
}
[void]$sb.AppendLine("];")
[IO.File]::WriteAllText($OutPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))

$byLvl = $list | Group-Object lvl | Sort-Object Name -Descending | ForEach-Object { "N$($_.Name): $($_.Count)" }
Write-Host "Wrote $($list.Count) entries ($([math]::Round((Get-Item $OutPath).Length/1KB)) KB) - $($byLvl -join ', ')"
